version: "3.9"
name: sfs

services:
  redis:
      image: redis:alpine3.17
      ports:
        - "6379:6379"
      restart: always
      command: >
          --requirepass testing

  classifier:
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ./src:/code/src
      - ./static:/code/static
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - redis
  

# docker compose -f ./docker-compose.yml up